name = "proxy-server"
main = "../../packages/proxy-server/src/worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

account_id = "61caa9d56c5a0143bfda0f07fd01088a"

[vars]
CONV_AGENT_URL = "https://conv-agent.yashrahmed.workers.dev"
WEB_ORIGIN = "https://proxy-server.yashrahmed.workers.dev"

[observability]
enabled = true
